version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - helloneele
  ignore:
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.3
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
