language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - "12"
  - "10"
scripts:
  - yarn run build
after_success:
  - yarn run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
